#!/bin/sh
sync_flag="/var/gluon/state/has_ntp_sync"
unsync_flag="/var/gluon/state/has_lost_ntp_sync"
[ $stratum = 16 ] && touch -a $unsync_flag && rm -f $sync_flag
[ $stratum -lt 16 ] && touch -a $sync_flag && rm -f $unsync_flag
